site_name: Bryan's Website!
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: indigo

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: light blue

nav:
  - Home: index.md
  - Content: content-tabs.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/bryanleyu/
    - icon: simple/github
      link: https://github.com/lelinyu

copyright: Copyright &copy; 2025 Bryan Yu